const projects = [
    {
        id: '1',
        title: 'The Serial Clayer',
        subheader: 'Design/Develop',
        image: '/images/the-serial-clayer-ss.png',
        description: 'E-Commerce site with Shopify Headless CMS.',
        subDescription: 'TypeScript, React, Framer-Motion, EmailJS, Styled Components',
        siteLink: 'https://www.theserialclayer.com/',
        codeLink: 'https://github.com/argounova/the-serial-clayer-commerce',
    },
    {
        id: '2',
        title: 'Turn17 Media',
        subheader: 'Design/Develop',
        image: '/images/turn17-screenshot-home.png',
        description: 'Website design and development.',
        subDescription: 'NextJS, Material UI, NextAuth, React, Framer-Motion, EmailJS, Styled Components',
        siteLink: 'https://www.turn17media.com/',
        codeLink: 'https://github.com/argounova/turn17-media',
    },
    {
        id: '3',
        title: 'Future Movement Beatz',
        subheader: 'Design/Develop',
        image: '/images/fmb-screenshot-home.png',
        description: 'Music production marketing and services site.',
        subDescription: 'Gatsby, React, Framer-Motion, EmailJS, Styled Components',
        siteLink: 'https://futuremovementbeatz.com/',
        codeLink: 'https://github.com/argounova/future-movement-beatz',
    },
    {
        id: '4',
        title: 'Wix Photography Portfolio',
        subheader: 'Design/Develop',
        image: '/images/cpwix-ss.png',
        description: 'Wix built site for photography portfolio.',
        subDescription: 'Wix, Custom coded drop-down',
        siteLink: 'https://craigliamphotography.wixsite.com/craigliam',
        codeLink: 'https://craigliamphotography.wixsite.com/craigliam',
    },
    {
        id: '5',
        title: 'Outta Touch',
        subheader: 'Design',
        image: '/images/outta-touch-ss.png',
        description: 'Instant messenger application built on React, utilizing a MongoDB database and installs locally.',
        subDescription: 'React, GraphQL, MongoDB, WebSocket',
        siteLink: 'https://outta-touch.herokuapp.com/',
        codeLink: 'https://github.com/argounova/outta-touch',
    },
    {
        id: '6',
        title: 'Magic:the Gathering',
        subheader: 'Design',
        image: '/images/mtg-ss.png',
        description: 'Create an account, login, and start building multiple decks from a daily-updated SDK.  Save, edit, and delete as many decks as you wish.',
        subDescription: 'MySQL, Skryfall SDK, Auto-complete, Dynamic Elements',
        siteLink: 'https://peaceful-escarpment-11973.herokuapp.com/',
        codeLink: 'https://github.com/HammontreeWebDev/MTGpp',
    },
    {
        id: '7',
        title: 'CP Photography',
        subheader: 'Design/Develop',
        image: '/images/cpp-ss.png',
        description: 'Gallery site, still in development.',
        subDescription: 'Gatsby, React',
        siteLink: 'https://cpphotography.art/',
        codeLink: 'https://github.com/argounova/cp-photography',
    },
    {
        id: '8',
        title: 'Password Generator',
        subheader: 'Design/Develop',
        image: '/images/password-generator-ss.png',
        description: 'Create random passwords with JavaScript functions, EmailJS for contact and a responsive design as highlighted features.',
        subDescription: 'JavaScript, EmailJS, Bootstrap',
        siteLink: 'https://argounova.github.io/password-generator/index.html',
        codeLink: 'https://github.com/argounova/password-generator',
    },
    {
        id: '9',
        title: 'Weather Dashboard',
        subheader: 'Design/Develop',
        image: '/images/weather-dashboard-ss.png',
        description: '5-day forecast data from a 3rd-party API, storing recent search history client-side and responsive design.',
        subDescription: '3rd-Party API, Client-side Storage, Responsive',
        siteLink: 'https://argounova.github.io/weather-dashboard/',
        codeLink: 'https://github.com/argounova/weather-dashboard',
    },
    {
        id: '10',
        title: 'Day Planner',
        subheader: 'Design/Develop',
        image: '/images/day-planner-ss.png',
        description: 'A mobile friendly design with local storage to remember your most important tasks.',
        subDescription: 'JavaScript, Client-side Storage, Responsive',
        siteLink: 'https://argounova.github.io/day-planner/',
        codeLink: 'https://github.com/argounova/day-planner',
    },   
]

export default projects