import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import '@fontsource/prosto-one'
import WorkSection from '../../components/WorkSection'
import EmailIcon from '@mui/icons-material/Email';
import { IconButton } from '@mui/material';

export default function Home() {
  return (
    <>
      <Head>
        <title>Craig Putzstuck | Developer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          <h1 className='largeHeading'>CRAIG PUTZSTUCK</h1>
          <p className='smallHeading'>front end design & full stack development</p>
          <IconButton aria-label='Email'>
            <EmailIcon sx={{ color: 'var(--color4)' }} />
          </IconButton>
        </div>
        <WorkSection />
      </main>
    </>
  )
}
